/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_nivalis9_coacd_CoacdNative_NativeBindings */

#ifndef _Included_io_github_nivalis9_coacd_CoacdNative_NativeBindings
#define _Included_io_github_nivalis9_coacd_CoacdNative_NativeBindings
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_nivalis9_coacd_CoacdNative_NativeBindings
 * Method:    decompose
 * Signature: ([D[IDIIIIIIIZZZIZDIJZ)[Lio/github/nivalis9/coacd/CoacdNative/Mesh;
 */
JNIEXPORT jobjectArray JNICALL Java_io_github_nivalis9_coacd_CoacdNative_00024NativeBindings_decompose
  (JNIEnv *, jclass, jdoubleArray, jintArray, jdouble, jint, jint, jint, jint, jint, jint, jint, jboolean, jboolean, jboolean, jint, jboolean, jdouble, jint, jlong, jboolean);

/*
 * Class:     io_github_nivalis9_coacd_CoacdNative_NativeBindings
 * Method:    setLogLevel
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_github_nivalis9_coacd_CoacdNative_00024NativeBindings_setLogLevel
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
